"""Network boot for a headless Spark, as a short-lived helper (never a standing service).

The point is a rescue path when a node's disk or OS is broken and nobody can plug in a keyboard:
the other Spark (or any Linux box on the same segment) answers the target's PXE request for a few
minutes and hands it a bootloader over TFTP.

What this really is: **proxyDHCP** via dnsmasq. It adds boot information to the answer your normal
DHCP server gives and never assigns addresses, so it cannot disturb a network that already has DHCP.
It is locked to ONE MAC address and stops by itself. It runs only when you start it (root, because
DHCP/TFTP use privileged ports) and the plan can be printed first without touching anything.

Not verified against DGX Spark firmware. Whether the Spark's UEFI offers a network boot entry, and
whether it can use the QSFP port for it, depends on the firmware version — `tsm node boot` lists what
it offers. Treat this as a documented recipe (docs/remote-management.md), not a promise.
"""

from __future__ import annotations

import ipaddress
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional

from .. import hostprobe

DEFAULT_MINUTES = 30
MAX_MINUTES = 240
_MAC = re.compile(r"^[0-9a-f]{2}(:[0-9a-f]{2}){5}$")
_IFACE = re.compile(r"^[A-Za-z0-9_.:-]{1,15}$")
_BOOTFILE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,120}$")
_MENU = "TwinSpark rescue boot"


class NetbootError(ValueError):
    pass


@dataclass
class NetbootPlan:
    mac: str
    iface: str
    network: str                    # network address the proxy range is announced on
    bootfile: str
    tftp_root: str
    minutes: int
    config: str
    steps: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def clean_mac(mac: str) -> str:
    m = (mac or "").strip().lower().replace("-", ":")
    if not _MAC.match(m):
        raise NetbootError(f"'{mac}' is not a MAC address (expected aa:bb:cc:dd:ee:ff)")
    return m


def render_config(mac: str, iface: str, network: str, bootfile: str, tftp_root: str) -> str:
    """The complete dnsmasq configuration. Every value is validated by the caller."""
    return "\n".join([
        "# Generated by `tsm netboot`. proxyDHCP for ONE machine; remove after use.",
        "# no DNS",
        "port=0",
        f"interface={iface}",
        "bind-interfaces",
        "log-dhcp",
        "# log to stderr",
        "log-facility=-",
        "# add boot information only; never hand out addresses",
        f"dhcp-range={network},proxy",
        f"dhcp-mac=set:target,{mac}",
        "# every other machine is left alone",
        "dhcp-ignore=tag:!target",
        f'pxe-service=tag:target,ARM64_EFI,"{_MENU}",{bootfile}',
        "enable-tftp",
        f"tftp-root={tftp_root}",
        "# some firmware mishandles blocksize negotiation",
        "tftp-no-blocksize",
        "",
    ])


def _network_of(iface: str, subnet: Optional[str], list_ifaces: Callable[[], list]) -> str:
    if subnet:
        try:
            return str(ipaddress.ip_network(subnet, strict=False).network_address)
        except ValueError as exc:
            raise NetbootError(f"'{subnet}' is not a network (e.g. 192.168.100.0/24)") from exc
    ifc = next((i for i in list_ifaces() if i.name == iface), None)
    if ifc is None:
        raise NetbootError(f"interface {iface} not found on this machine")
    if not ifc.ipv4:
        raise NetbootError(f"interface {iface} has no IPv4 address; give --subnet or configure it first")
    return str(ipaddress.ip_interface(ifc.ipv4[0]).network.network_address)


def build_plan(mac: str, iface: str, bootfile: str, tftp_root: str, *, subnet: Optional[str] = None,
               minutes: int = DEFAULT_MINUTES,
               list_ifaces: Callable[[], list] = hostprobe.list_interfaces,
               which: Callable[[str], Optional[str]] = shutil.which) -> NetbootPlan:
    mac = clean_mac(mac)
    if not _IFACE.match(iface or ""):
        raise NetbootError(f"'{iface}' is not a valid interface name")
    if not _BOOTFILE.match(bootfile or "") or ".." in bootfile.split("/"):
        raise NetbootError("bootfile must be a relative path below the TFTP root (letters, digits, . _ - /)")
    root = Path(tftp_root)
    if not root.is_absolute() or any(c in str(root) for c in "\n\r\"' ,"):
        raise NetbootError("tftp root must be an absolute path without spaces or quotes")
    if isinstance(minutes, bool) or not isinstance(minutes, int) or not 1 <= minutes <= MAX_MINUTES:
        raise NetbootError(f"minutes must be between 1 and {MAX_MINUTES}")
    network = _network_of(iface, subnet, list_ifaces)

    warnings: list[str] = []
    if not root.is_dir():
        warnings.append(f"TFTP root {root} does not exist yet")
    elif not (root / bootfile).is_file():
        warnings.append(f"{root / bootfile} is missing: put an ARM64 UEFI network bootloader there "
                        f"(for example iPXE's snp.arm64.efi or GRUB's grubnetaa64.efi)")
    if not which("dnsmasq"):
        warnings.append("dnsmasq is not installed: sudo apt install dnsmasq-base")

    cfg = render_config(mac, iface, network, bootfile, str(root))
    steps = [
        f"Put the bootloader at {root / bootfile} (ARM64 UEFI, small; it fetches the rest over the network)",
        f"Start the helper (needs root):  sudo tsm netboot serve --mac {mac} --iface {iface} "
        f"--bootfile {bootfile} --tftp-root {root}",
        "In another terminal tell the target to boot from the network once:  tsm remote boot <node> network",
        "Reboot the target:  tsm remote reboot <node>   (or cycle its smart plug)",
        f"The helper logs every DHCP/TFTP request from {mac}. If none arrives, the firmware is not trying "
        f"the network on that port",
        f"It stops by itself after {minutes} minutes. Nothing stays installed or running.",
    ]
    return NetbootPlan(mac, iface, network, bootfile, str(root), minutes, cfg, steps, warnings)


def serve(plan: NetbootPlan, *, popen: Callable = subprocess.Popen, which: Callable = shutil.which,
          out=None) -> int:
    """Run dnsmasq in the foreground for at most ``plan.minutes``. Returns its exit code."""
    exe = which("dnsmasq")
    if not exe:
        raise NetbootError("dnsmasq is not installed: sudo apt install dnsmasq-base")
    if not Path(plan.tftp_root).is_dir():
        raise NetbootError(f"TFTP root {plan.tftp_root} does not exist")
    with tempfile.TemporaryDirectory(prefix="tsm-netboot-") as tmp:
        conf = Path(tmp) / "dnsmasq.conf"
        conf.write_text(plan.config)
        conf.chmod(0o600)
        proc = popen([exe, "--keep-in-foreground", f"--conf-file={conf}"], stdout=out, stderr=subprocess.STDOUT)
        try:
            return proc.wait(timeout=plan.minutes * 60)
        except subprocess.TimeoutExpired:
            proc.terminate()
            try:
                return proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
                return proc.wait()
        except KeyboardInterrupt:
            proc.terminate()
            return proc.wait()
